// Replays the recorded CLI API request/response BODY contract of the real upstream
// hot-updater packages against the Rust types in `src/routes/api.rs`.
// Fixtures generated by `tests/generate_cli_api_fixtures.mjs`.
//
//   bundleResponseCases -- GET /api/bundles/:id   -> ClientBundle / ClientPatch
//   envelopeCases       -- GET /api/bundles, /channels
//   createBundleCases   -- POST /api/bundles      -> CLIBundle / CLIPatch
//   updateBundleCases   -- PATCH /api/bundles/:id -> UpdateBundlePayload
//   deleteBundleCases   -- DELETE /api/bundles/:id
//
// TWO-STAGE STRUCTURE -- please keep it, exactly as in `tests/pagination_parity_tests.rs`.
// Every case is checked FIRST against the documented upstream rule (does the RECORDED
// fixture still obey it?) and only THEN against the Rust type. Collapsing the two would make
// "upstream moved" and "we regressed" present identically. Stage-one messages say
// RECORDED FIXTURE explicitly.
//
// WHAT THIS FILE REACHES. Everything runs with no database, against pure functions exported
// from `src/routes/api.rs` -- the pattern `calculate_pagination` and `build_cursor_page_query`
// already set:
//
//   map_to_client_bundle          the row -> response body mapping (upstream `rowToBundle`)
//   parse_bundle_metadata         the metadata column's absent-vs-null rule
//   parse_target_cohorts          upstream `parseTargetCohorts`
//   get_bundle_patches            upstream `readBundlePatchArray` + `getBundlePatches`
//   require_bundle_patch_payload  upstream `requireBundlePatchPayload`
//
// Still NOT reachable, and recorded rather than replayed: the HTTP status codes, the
// `{"success": true}` literals, and the defaults `create_bundles` applies (`enabled` -> true,
// `channel` -> "production"). See the module comment at the bottom of this file.
use rn_ota_server_rust::models::{Bundle, BundlePatch};
use rn_ota_server_rust::routes::api::{
    get_bundle_patches, map_to_client_bundle, merge_bundle_metadata, parse_bundle_metadata,
    require_bundle_patch_payload, CLIBundle, ClientBundle, UpdateBundlePayload,
};
use serde::Deserialize;
use serde_json::{Map, Value};

/// Rebuild the `bundles` row the recorded case was served from, so it can be pushed through
/// `map_to_client_bundle` — the Rust counterpart of upstream's `rowToBundle`.
///
/// `app_name` and `ctime` exist only on this server (the multi-app column and an audit
/// timestamp) and neither reaches the response body, so they are filled with placeholders.
/// A `null` `rollout_cohort_count` in the fixture stands for a column MySQL never lets be
/// null — `INT NOT NULL DEFAULT 1000` — which lands on the same 1000 upstream's
/// `?? DEFAULT_ROLLOUT_COHORT_COUNT` produces.
fn row_to_bundle(row: &Value) -> Bundle {
    let s = |k: &str| row.get(k).and_then(Value::as_str).map(str::to_string);
    let req = |k: &str| s(k).unwrap_or_else(|| panic!("fixture row is missing '{k}'"));
    let json = |k: &str| match row.get(k) {
        None | Some(Value::Null) => None,
        Some(v) => Some(v.clone()),
    };
    // MySQL `TINYINT(1)`: the fixture records both the integer and the boolean spelling.
    let flag = |k: &str| match row.get(k) {
        Some(Value::Bool(b)) => i8::from(*b),
        Some(Value::Number(n)) => n.as_i64().unwrap_or(0) as i8,
        _ => 0,
    };

    Bundle {
        id: req("id"),
        app_name: "fixture-app".to_string(),
        platform: req("platform"),
        should_force_update: flag("should_force_update"),
        enabled: flag("enabled"),
        file_hash: req("file_hash"),
        git_commit_hash: s("git_commit_hash"),
        message: s("message"),
        channel: req("channel"),
        storage_uri: req("storage_uri"),
        target_app_version: s("target_app_version"),
        fingerprint_hash: s("fingerprint_hash"),
        metadata: json("metadata"),
        rollout_cohort_count: row
            .get("rollout_cohort_count")
            .and_then(Value::as_i64)
            .unwrap_or(1000) as i32,
        target_cohorts: json("target_cohorts"),
        manifest_storage_uri: s("manifest_storage_uri"),
        manifest_file_hash: s("manifest_file_hash"),
        asset_base_storage_uri: s("asset_base_storage_uri"),
        ctime: chrono::DateTime::UNIX_EPOCH,
    }
}

/// Rebuild the `bundle_patches` rows, in the order the server's
/// `ORDER BY order_index ASC` would hand them back.
fn rows_to_patches(rows: &[Value]) -> Vec<BundlePatch> {
    let mut patches: Vec<(i32, BundlePatch)> = rows
        .iter()
        .map(|r| {
            let s = |k: &str| {
                r.get(k)
                    .and_then(Value::as_str)
                    .unwrap_or_default()
                    .to_string()
            };
            let order_index = r.get("order_index").and_then(Value::as_i64).unwrap_or(0) as i32;
            (
                order_index,
                BundlePatch {
                    id: s("id"),
                    bundle_id: s("bundle_id"),
                    base_bundle_id: s("base_bundle_id"),
                    base_file_hash: s("base_file_hash"),
                    patch_file_hash: s("patch_file_hash"),
                    patch_storage_uri: s("patch_storage_uri"),
                    order_index,
                    ctime: chrono::DateTime::UNIX_EPOCH,
                },
            )
        })
        .collect();

    // Upstream's `rowToBundle` sorts by `order_index` and breaks a tie on `base_bundle_id`;
    // MySQL's `ORDER BY order_index ASC` leaves ties unspecified, so the tie-break is
    // applied here to match what the SQL layer would have to guarantee.
    patches.sort_by(|(ai, a), (bi, b)| {
        ai.cmp(bi)
            .then_with(|| a.base_bundle_id.cmp(&b.base_bundle_id))
    });
    patches.into_iter().map(|(_, p)| p).collect()
}

// =====================================================================================
// The documented upstream rules the stage-one checks are written against.
// =====================================================================================

/// The key set `rowToBundle` (`@hot-updater/server` `dist/db/bundleRows.mjs`) emits, which
/// is what `handleGetBundle` JSON.stringifies straight onto the wire. All four shipped SQL
/// adapters map their rows with this function, so it is upstream's row <-> Bundle contract.
const BUNDLE_KEYS: &[&str] = &[
    "id",
    "platform",
    "shouldForceUpdate",
    "enabled",
    "fileHash",
    "gitCommitHash",
    "message",
    "channel",
    "storageUri",
    "targetAppVersion",
    "fingerprintHash",
    "metadata",
    "manifestStorageUri",
    "manifestFileHash",
    "assetBaseStorageUri",
    "patches",
    "patchBaseBundleId",
    "patchBaseFileHash",
    "patchFileHash",
    "patchStorageUri",
    "rolloutCohortCount",
    "targetCohorts",
];

/// The ONLY key upstream ever omits from a bundle body. `rowToBundle` sets
/// `metadata: parseBundleMetadata(record.metadata)`, and `parseBundleMetadata` returns
/// `undefined` -- not `null`, not `{}` -- for a null, unparseable, array or non-object
/// column value. `JSON.stringify` then drops the key entirely. Every other key is always
/// present, carrying `null` when it has no value.
const OPTIONAL_BUNDLE_KEY: &str = "metadata";

const PATCH_KEYS: &[&str] = &[
    "baseBundleId",
    "baseFileHash",
    "patchFileHash",
    "patchStorageUri",
];

/// The columns `bundleToRow` writes. Anything outside this set may be merged into upstream's
/// in-memory bundle but never reaches storage, so a PATCH naming it is a no-op once the row
/// round-trips through the database.
///
/// `patches` is here even though `bundleToRow` does not emit it: it becomes rows of its own
/// via `bundleToPatchRows`.
const ROW_COLUMNS: &[&str] = &[
    "id",
    "platform",
    "should_force_update",
    "enabled",
    "file_hash",
    "git_commit_hash",
    "message",
    "channel",
    "storage_uri",
    "target_app_version",
    "fingerprint_hash",
    "metadata",
    "manifest_storage_uri",
    "manifest_file_hash",
    "asset_base_storage_uri",
    "rollout_cohort_count",
    "target_cohorts",
];

/// Every field a PATCH can actually change in storage. `id` is excluded because
/// `requireBundlePatchPayload` strips it.
///
/// **The four deprecated flat patch fields are deliberately NOT here** — `patchBaseBundleId`,
/// `patchBaseFileHash`, `patchFileHash`, `patchStorageUri`. `mergeBundleUpdate` does merge
/// them into upstream's in-memory bundle, but `bundleToRow` has no column for any of them and
/// `bundleToPatchRows` reads only `patches`, so they never reach storage and are regenerated
/// from `patches[0]` on the way back out. The recorded case "the deprecated flat patch fields
/// are patchable too" shows exactly that: 200, and a persisted row with no new column and no
/// new patch row. `test_update_payload_parity` proves the column set from the fixture rather
/// than trusting this comment — see the `ROW_COLUMNS` stage-one check.
const PATCHABLE_KEYS: &[&str] = &[
    "platform",
    "shouldForceUpdate",
    "enabled",
    "fileHash",
    "gitCommitHash",
    "message",
    "channel",
    "storageUri",
    "targetAppVersion",
    "fingerprintHash",
    "metadata",
    "manifestStorageUri",
    "manifestFileHash",
    "assetBaseStorageUri",
    "patches",
    "rolloutCohortCount",
    "targetCohorts",
];

// =====================================================================================
// Fixture types
// =====================================================================================

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct BundleResponseCase {
    description: String,
    /// The snake_case DATABASE ROW that produced the body — the same columns
    /// `migrations/20260714000000_init.sql` declares.
    row: Option<Value>,
    patch_rows: Vec<Value>,
    status: u16,
    content_type: Option<String>,
    bundle_keys: Option<Vec<String>>,
    bundle: Value,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct EnvelopeCase {
    description: String,
    path: String,
    status: u16,
    body_keys: Option<Vec<String>>,
    data_element_keys: Option<Vec<String>>,
    pagination_keys: Option<Vec<String>>,
    body: Value,
}

/// What upstream forwarded to `appendBundle` / `updateBundle`, with the key list recorded
/// separately: `JSON.stringify` erases an `undefined` value, and absent-vs-null is exactly
/// the distinction these cases exist to pin.
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct RecordedPayload {
    keys: Option<Vec<String>>,
    value: Value,
}

/// A row as `bundleToRow` / `bundleToPatchRows` produced it. `undefinedKeys` names the
/// columns upstream handed the adapter nothing for — `JSON.stringify` drops an `undefined`
/// value, so without this list "no default was applied" is invisible in `value`.
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct PersistedRow {
    #[allow(dead_code)]
    undefined_keys: Vec<String>,
    value: Value,
}

#[derive(Deserialize)]
struct PersistedRows {
    #[allow(dead_code)]
    bundles: Vec<PersistedRow>,
    patches: Vec<PersistedRow>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct CreateBundleCase {
    description: String,
    request_body: Value,
    request_body_is_raw_text: bool,
    status: u16,
    body: Value,
    appended: Vec<RecordedPayload>,
    persisted: PersistedRows,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct UpdateBundleCase {
    description: String,
    target_id: String,
    request_body: Value,
    request_body_is_raw_text: bool,
    before_rows: Vec<Value>,
    status: u16,
    body: Value,
    patch_payload: Option<RecordedPayload>,
    persisted: PersistedRows,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct DeleteBundleCase {
    description: String,
    status: u16,
    body: Value,
    delete_calls: u32,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Fixtures {
    bundle_response_cases: Vec<BundleResponseCase>,
    envelope_cases: Vec<EnvelopeCase>,
    create_bundle_cases: Vec<CreateBundleCase>,
    update_bundle_cases: Vec<UpdateBundleCase>,
    delete_bundle_cases: Vec<DeleteBundleCase>,
}

fn load() -> Fixtures {
    let json = std::fs::read_to_string("tests/fixtures/cli_api_fixtures.json")
        .expect("Failed to read tests/fixtures/cli_api_fixtures.json");
    serde_json::from_str(&json).expect("Failed to parse cli_api_fixtures.json")
}

fn report(failures: &[String], what: &str) {
    assert!(
        failures.is_empty(),
        "{} of the recorded upstream {} results do not match the Rust implementation:\n\n{}\n",
        failures.len(),
        what,
        failures.join("\n\n")
    );
}

fn object(value: &Value) -> Option<&Map<String, Value>> {
    value.as_object()
}

fn keys_of(value: &Value) -> Vec<String> {
    object(value)
        .map(|m| m.keys().cloned().collect())
        .unwrap_or_default()
}

/// A stable, order-independent rendering of a key list. JSON object key order carries no
/// meaning over the wire, so every comparison in this file is on key SETS -- but the
/// fixture records the emission order too, so a field that silently disappears upstream is
/// still visible in `git diff tests/fixtures/`.
fn sorted(keys: &[String]) -> Vec<String> {
    let mut v = keys.to_vec();
    v.sort();
    v
}

fn sorted_str(keys: &[&str]) -> Vec<String> {
    sorted(&keys.iter().map(|s| (*s).to_string()).collect::<Vec<_>>())
}

// =====================================================================================
// 1. The bundle RESPONSE body: GET /api/bundles/:id
// =====================================================================================

/// The Rust response type must describe upstream's body exactly: it must be able to
/// RECEIVE the recorded body and RE-EMIT it with the same key set and the same values.
///
/// Both directions matter and they fail differently. A field upstream sends that
/// `ClientBundle` cannot hold fails the deserialize; a field `ClientBundle` emits that
/// upstream does not (or a key upstream omits that Rust materialises) shows up in the key
/// set of the re-serialized value. The pagination work established that upstream *omits*
/// keys rather than nulling them and that JSON serialization erases the difference; the
/// same care applies here, which is why the key sets are compared explicitly rather than
/// left implicit in a value comparison.
#[test]
fn test_bundle_response_body_parity() {
    let mut failures = Vec::new();
    let canonical = sorted_str(BUNDLE_KEYS);

    for case in load().bundle_response_cases {
        if case.status != 200 {
            // The only non-200 in this group is the 404, checked separately below.
            continue;
        }

        let recorded_keys = case.bundle_keys.clone().unwrap_or_default();

        // ---- Stage 1: does the RECORDED fixture still obey rowToBundle's documented rule?
        let recorded_sorted = sorted(&recorded_keys);
        let unknown: Vec<&String> = recorded_keys
            .iter()
            .filter(|k| !BUNDLE_KEYS.contains(&k.as_str()))
            .collect();
        if !unknown.is_empty() {
            failures.push(format!(
                "case '{}' -- RECORDED FIXTURE carries keys rowToBundle does not emit: {:?}\n    recorded : {:?}\n    canonical: {:?}",
                case.description, unknown, recorded_keys, BUNDLE_KEYS,
            ));
            continue;
        }
        let missing: Vec<&&str> = BUNDLE_KEYS
            .iter()
            .filter(|k| **k != OPTIONAL_BUNDLE_KEY && !recorded_keys.iter().any(|r| r == *k))
            .collect();
        if !missing.is_empty() {
            failures.push(format!(
                "case '{}' -- RECORDED FIXTURE omits keys that upstream always emits: {:?}\n    only '{}' may ever be absent (parseBundleMetadata returns undefined for a null/unparseable/non-object column)",
                case.description, missing, OPTIONAL_BUNDLE_KEY,
            ));
            continue;
        }
        // The deprecated flat patch fields must mirror patches[0], or be null when there is
        // no patch at all. This is what makes them "deprecated mirrors" rather than
        // independent columns, and it is the rule `map_to_client_bundle` reproduces.
        let patches = case.bundle.get("patches").and_then(Value::as_array);
        let primary = patches.and_then(|p| p.first());
        for (mirror, source) in [
            ("patchBaseBundleId", "baseBundleId"),
            ("patchBaseFileHash", "baseFileHash"),
            ("patchFileHash", "patchFileHash"),
            ("patchStorageUri", "patchStorageUri"),
        ] {
            let want = primary
                .and_then(|p| p.get(source))
                .cloned()
                .unwrap_or(Value::Null);
            let got = case.bundle.get(mirror).cloned().unwrap_or(Value::Null);
            if want != got {
                failures.push(format!(
                    "case '{}' -- RECORDED FIXTURE breaks the patch-mirror rule: {} is {:?} but patches[0].{} is {:?}",
                    case.description, mirror, got, source, want,
                ));
            }
        }
        if let Some(list) = patches {
            for (i, patch) in list.iter().enumerate() {
                let got = sorted(&keys_of(patch));
                if got != sorted_str(PATCH_KEYS) {
                    failures.push(format!(
                        "case '{}' -- RECORDED FIXTURE patches[{}] has key set {:?}, not upstream's {:?}",
                        case.description, i, got, PATCH_KEYS,
                    ));
                }
            }
        }
        if recorded_sorted != canonical
            && recorded_sorted
                != canonical
                    .iter()
                    .filter(|k| k.as_str() != OPTIONAL_BUNDLE_KEY)
                    .cloned()
                    .collect::<Vec<_>>()
        {
            failures.push(format!(
                "case '{}' -- RECORDED FIXTURE key set {:?} is neither the canonical set nor the canonical set minus '{}'",
                case.description, recorded_sorted, OPTIONAL_BUNDLE_KEY,
            ));
            continue;
        }

        // ---- Stage 2a: the Rust response TYPE must be able to receive upstream's body.
        // A field upstream sends that `ClientBundle` cannot hold fails right here.
        let parsed: ClientBundle = match serde_json::from_value(case.bundle.clone()) {
            Ok(b) => b,
            Err(err) => {
                failures.push(format!(
                    "case '{}' -- the Rust response type CANNOT REPRESENT upstream's body\n    upstream body keys : {:?}\n    serde error        : {}\n    upstream body      : {}",
                    case.description,
                    recorded_keys,
                    err,
                    serde_json::to_string(&case.bundle).unwrap_or_default(),
                ));
                continue;
            }
        };

        // ---- Stage 2b: and the Rust ROW MAPPING must produce that body from the row the
        // case was served from. This is the stronger of the two: it pins the metadata
        // parsing, the patch ordering and the target_cohorts parsing, none of which the
        // round trip in 2a can see.
        let row = case.row.as_ref().expect("a 200 case records its row");
        let mapped = map_to_client_bundle(row_to_bundle(row), rows_to_patches(&case.patch_rows));
        let mapped_value = serde_json::to_value(&mapped).expect("ClientBundle serializes");
        if mapped_value != case.bundle {
            let all_keys: Vec<String> = {
                let mut k = recorded_keys.clone();
                k.extend(keys_of(&mapped_value));
                k.sort();
                k.dedup();
                k
            };
            let differing: Vec<String> = all_keys
                .iter()
                .filter(|k| mapped_value.get(*k) != case.bundle.get(*k))
                .map(|k| {
                    format!(
                        "      {}: upstream {} / rust {}",
                        k,
                        case.bundle
                            .get(k)
                            .map(ToString::to_string)
                            .unwrap_or_else(|| "<KEY ABSENT>".into()),
                        mapped_value
                            .get(k)
                            .map(ToString::to_string)
                            .unwrap_or_else(|| "<KEY ABSENT>".into()),
                    )
                })
                .collect();
            failures.push(format!(
                "case '{}' -- map_to_client_bundle does not reproduce upstream's body from the row\n    row : {}\n{}",
                case.description,
                serde_json::to_string(row).unwrap_or_default(),
                differing.join("\n"),
            ));
            continue;
        }

        let reemitted = serde_json::to_value(&parsed).expect("ClientBundle serializes");
        let rust_keys = sorted(&keys_of(&reemitted));
        if rust_keys != recorded_sorted {
            let extra: Vec<&String> = rust_keys
                .iter()
                .filter(|k| !recorded_sorted.contains(k))
                .collect();
            let dropped: Vec<&String> = recorded_sorted
                .iter()
                .filter(|k| !rust_keys.contains(k))
                .collect();
            failures.push(format!(
                "case '{}' -- key set differs\n    upstream emits : {:?}\n    rust emits     : {:?}\n    rust adds      : {:?}\n    rust drops     : {:?}",
                case.description, recorded_sorted, rust_keys, extra, dropped,
            ));
            continue;
        }

        if reemitted != case.bundle {
            let differing: Vec<String> = recorded_keys
                .iter()
                .filter(|k| reemitted.get(*k) != case.bundle.get(*k))
                .map(|k| {
                    format!(
                        "      {}: upstream {} / rust {}",
                        k,
                        case.bundle
                            .get(k)
                            .map(ToString::to_string)
                            .unwrap_or_else(|| "<absent>".into()),
                        reemitted
                            .get(k)
                            .map(ToString::to_string)
                            .unwrap_or_else(|| "<absent>".into()),
                    )
                })
                .collect();
            failures.push(format!(
                "case '{}' -- values differ after the round trip\n{}",
                case.description,
                differing.join("\n"),
            ));
        }
    }

    report(&failures, "bundle response body");
}

/// The 404 body is a JSON object, not bare text: `{"error": "Bundle not found"}` with
/// `Content-Type: application/json` (handler.mjs:126-129).
#[test]
fn test_bundle_not_found_body_is_recorded() {
    let mut failures = Vec::new();

    for case in load().bundle_response_cases {
        if case.status == 200 {
            continue;
        }
        if case.status != 404
            || case.bundle != serde_json::json!({ "error": "Bundle not found" })
            || case.content_type.as_deref() != Some("application/json")
        {
            failures.push(format!(
                "case '{}' -- RECORDED FIXTURE no longer carries upstream's 404 contract\n    recorded : status {} content-type {:?} body {}\n    upstream : status 404 content-type \"application/json\" body {{\"error\":\"Bundle not found\"}}",
                case.description,
                case.status,
                case.content_type,
                case.bundle,
            ));
        }
    }

    report(&failures, "bundle 404 body");
}

// =====================================================================================
// 2. The list and channels envelopes
// =====================================================================================

/// Stage one for the envelopes, plus the one stage-two check that is reachable without a
/// database: a bundle inside the list `data` array must be the SAME shape as the one the
/// single-bundle route returns, so `ClientBundle` has to describe it too.
///
/// The envelope builders themselves (`{"data": …, "pagination": …}` in `list_bundles`,
/// `{"data": {"channels": …}}` in `list_channels`) are inline in async handler bodies and
/// cannot be replayed here.
#[test]
fn test_envelope_body_parity() {
    let mut failures = Vec::new();

    for case in load().envelope_cases {
        if case.status != 200 {
            failures.push(format!(
                "envelope case '{}' -- RECORDED FIXTURE unexpectedly has status {}",
                case.description, case.status,
            ));
            continue;
        }

        let is_channels = case.path.contains("/channels");
        let body_keys = sorted(&case.body_keys.clone().unwrap_or_default());

        // ---- Stage 1: the documented envelope shapes.
        if is_channels {
            let channels = case.body.get("data").and_then(|d| d.get("channels"));
            if body_keys != vec!["data".to_string()]
                || case.body.get("data").map(keys_of).map(|k| sorted(&k))
                    != Some(vec!["channels".to_string()])
                || !matches!(channels, Some(Value::Array(_)))
            {
                failures.push(format!(
                    "channels case '{}' -- RECORDED FIXTURE is not upstream's {{\"data\":{{\"channels\":[…]}}}} shape: {}",
                    case.description, case.body,
                ));
            }
            continue;
        }

        if body_keys != vec!["data".to_string(), "pagination".to_string()] {
            failures.push(format!(
                "list case '{}' -- RECORDED FIXTURE envelope keys are {:?}, not upstream's [\"data\", \"pagination\"]",
                case.description, body_keys,
            ));
            continue;
        }
        // The cursor keys are omitted, never nulled -- same rule the pagination suite pins.
        let pagination_keys = case.pagination_keys.clone().unwrap_or_default();
        let base = [
            "total",
            "hasNextPage",
            "hasPreviousPage",
            "currentPage",
            "totalPages",
        ];
        let unexpected: Vec<&String> = pagination_keys
            .iter()
            .filter(|k| {
                !base.contains(&k.as_str())
                    && k.as_str() != "nextCursor"
                    && k.as_str() != "previousCursor"
            })
            .collect();
        if !unexpected.is_empty() || base.iter().any(|b| !pagination_keys.iter().any(|k| k == b)) {
            failures.push(format!(
                "list case '{}' -- RECORDED FIXTURE pagination keys {:?} are not the five base keys plus the optional cursor keys",
                case.description, pagination_keys,
            ));
            continue;
        }

        // ---- Stage 2: a list element is a full bundle, describable by ClientBundle.
        let Some(element) = case
            .body
            .get("data")
            .and_then(Value::as_array)
            .and_then(|a| a.first())
        else {
            continue;
        };
        let element_keys = sorted(&case.data_element_keys.clone().unwrap_or_default());
        if element_keys != sorted_str(BUNDLE_KEYS)
            && element_keys
                != sorted_str(BUNDLE_KEYS)
                    .into_iter()
                    .filter(|k| k != OPTIONAL_BUNDLE_KEY)
                    .collect::<Vec<_>>()
        {
            failures.push(format!(
                "list case '{}' -- RECORDED FIXTURE list element key set {:?} differs from the single-bundle route's",
                case.description, element_keys,
            ));
            continue;
        }
        match serde_json::from_value::<ClientBundle>(element.clone()) {
            Ok(parsed) => {
                let reemitted = serde_json::to_value(&parsed).expect("ClientBundle serializes");
                if sorted(&keys_of(&reemitted)) != element_keys {
                    failures.push(format!(
                        "list case '{}' -- rust re-emits list-element keys {:?}, upstream emitted {:?}",
                        case.description,
                        sorted(&keys_of(&reemitted)),
                        element_keys,
                    ));
                }
            }
            Err(err) => failures.push(format!(
                "list case '{}' -- the Rust response type CANNOT REPRESENT a list element\n    serde error : {}\n    element     : {}",
                case.description, err, element,
            )),
        }
    }

    report(&failures, "envelope body");
}

// =====================================================================================
// 3. POST /api/bundles -- the CLIBundle request body
// =====================================================================================

/// The camelCase field names `CLIBundle` accepts, reported by probing the parsed struct.
/// Returns the names whose value came through as `Some`/present.
fn cli_bundle_present_fields(b: &CLIBundle) -> Vec<&'static str> {
    let mut present = vec!["id", "platform", "fileHash", "storageUri"];
    if b.should_force_update.is_some() {
        present.push("shouldForceUpdate");
    }
    if b.enabled.is_some() {
        present.push("enabled");
    }
    if b.git_commit_hash.is_some() {
        present.push("gitCommitHash");
    }
    if b.message.is_some() {
        present.push("message");
    }
    if b.channel.is_some() {
        present.push("channel");
    }
    if b.target_app_version.is_some() {
        present.push("targetAppVersion");
    }
    if b.fingerprint_hash.is_some() {
        present.push("fingerprintHash");
    }
    if b.metadata.is_some() {
        present.push("metadata");
    }
    if b.rollout_cohort_count.is_some() {
        present.push("rolloutCohortCount");
    }
    if b.target_cohorts.is_some() {
        present.push("targetCohorts");
    }
    if b.manifest_storage_uri.is_some() {
        present.push("manifestStorageUri");
    }
    if b.manifest_file_hash.is_some() {
        present.push("manifestFileHash");
    }
    if b.asset_base_storage_uri.is_some() {
        present.push("assetBaseStorageUri");
    }
    if b.patches.is_some() {
        present.push("patches");
    }
    present
}

#[test]
fn test_create_payload_parity() {
    let mut failures = Vec::new();

    for case in load().create_bundle_cases {
        if case.request_body_is_raw_text {
            // A body that is not a JSON object at all. Upstream reaches
            // assertBundlePersistenceConstraints with it and answers 500; the Rust side
            // cannot even build a CLIBundle. There is no shape to compare -- these cases
            // exist to record upstream's answer, which is reported rather than replayed.
            continue;
        }

        let bundles: Vec<Value> = match &case.request_body {
            Value::Array(items) => items.clone(),
            other => vec![other.clone()],
        };

        // ---- Stage 1: handleCreateBundles forwards each element VERBATIM. Nothing at the
        // HTTP layer inspects, defaults or reshapes the payload, so what appendBundle saw
        // must be byte-identical to what was posted -- for every element upstream got to.
        for (i, recorded) in case.appended.iter().enumerate() {
            let Some(sent) = bundles.get(i) else {
                failures.push(format!(
                    "create case '{}' -- RECORDED FIXTURE has more appendBundle calls ({}) than posted bundles ({})",
                    case.description,
                    case.appended.len(),
                    bundles.len(),
                ));
                break;
            };
            if &recorded.value != sent {
                failures.push(format!(
                    "create case '{}' -- RECORDED FIXTURE shows the payload being reshaped before appendBundle, but upstream forwards it verbatim\n    posted   : {}\n    appended : {}",
                    case.description, sent, recorded.value,
                ));
                continue;
            }
            if recorded.keys.as_ref().map(|k| sorted(k)) != Some(sorted(&keys_of(sent))) {
                failures.push(format!(
                    "create case '{}' -- RECORDED FIXTURE key list {:?} does not match the posted body's {:?}",
                    case.description,
                    recorded.keys,
                    keys_of(sent),
                ));
            }
        }

        // ---- Stage 2: the Rust request type must accept everything upstream accepted, and
        // must capture the same field values.
        let upstream_accepted = case.status == 201;
        for (i, sent) in bundles.iter().enumerate() {
            let parsed = serde_json::from_value::<CLIBundle>(sent.clone());

            match (&parsed, upstream_accepted) {
                (Err(err), true) => {
                    failures.push(format!(
                        "create case '{}' bundle[{}] -- upstream ACCEPTED this payload (201 {}), the Rust type REJECTS it\n    payload     : {}\n    serde error : {}",
                        case.description, i, case.body, sent, err,
                    ));
                    continue;
                }
                (Ok(_), false) => {
                    // Not a failure on its own: upstream's rejection may come from
                    // assertBundlePersistenceConstraints, which is downstream of the shape
                    // and is not part of the serde contract. Nothing to assert here.
                    continue;
                }
                (Err(_), false) => continue,
                (Ok(_), true) => {}
            }

            let parsed = parsed.expect("checked above");

            // Which fields did each side see? Upstream's answer is the posted key set
            // restricted to fields the CLIBundle contract knows about; Rust's is which
            // options came through as Some. An explicit `null` is what separates them:
            // upstream sees the key, serde folds it to None.
            let posted_keys = keys_of(sent);
            let rust_present = cli_bundle_present_fields(&parsed);
            for key in &posted_keys {
                let known = matches!(
                    key.as_str(),
                    "id" | "platform"
                        | "shouldForceUpdate"
                        | "enabled"
                        | "fileHash"
                        | "gitCommitHash"
                        | "message"
                        | "channel"
                        | "storageUri"
                        | "targetAppVersion"
                        | "fingerprintHash"
                        | "metadata"
                        | "rolloutCohortCount"
                        | "targetCohorts"
                        | "manifestStorageUri"
                        | "manifestFileHash"
                        | "assetBaseStorageUri"
                        | "patches"
                );
                if !known {
                    // Upstream forwards unknown keys; bundleToRow then drops them, so they
                    // never reach a column. serde ignoring them is the same outcome.
                    continue;
                }
                let sent_null = sent.get(key) == Some(&Value::Null);
                let rust_saw = rust_present.contains(&key.as_str());
                if !rust_saw && !sent_null {
                    failures.push(format!(
                        "create case '{}' bundle[{}] -- field '{}' was posted with value {} and upstream forwarded it, but the Rust type did not capture it",
                        case.description,
                        i,
                        key,
                        sent.get(key).map(ToString::to_string).unwrap_or_default(),
                    ));
                }
            }

            // The patches array, replayed against the rows upstream actually PERSISTED --
            // which is `bundleToPatchRows(getBundlePatches(bundle))`, i.e. after the
            // malformed entries and the repeated bases have been dropped. Comparing against
            // the posted array instead would miss exactly the filtering this pins.
            let upstream_rows: Vec<&Value> = case
                .persisted
                .patches
                .iter()
                .map(|r| &r.value)
                .filter(|r| r.get("bundle_id") == sent.get("id"))
                .collect();
            let rust_patches = get_bundle_patches(parsed.patches.as_ref());

            if rust_patches.len() != upstream_rows.len() {
                failures.push(format!(
                    "create case '{}' bundle[{}] -- upstream persisted {} patch row(s), rust derives {}\n    posted patches : {}",
                    case.description,
                    i,
                    upstream_rows.len(),
                    rust_patches.len(),
                    sent.get("patches").map(ToString::to_string).unwrap_or_else(|| "<absent>".into()),
                ));
                continue;
            }
            for (j, upstream_row) in upstream_rows.iter().enumerate() {
                let rust_patch = &rust_patches[j];
                let want = (
                    upstream_row.get("base_bundle_id").and_then(Value::as_str),
                    upstream_row.get("base_file_hash").and_then(Value::as_str),
                    upstream_row.get("patch_file_hash").and_then(Value::as_str),
                    upstream_row
                        .get("patch_storage_uri")
                        .and_then(Value::as_str),
                    upstream_row.get("order_index").and_then(Value::as_i64),
                );
                let got = (
                    Some(rust_patch.base_bundle_id.as_str()),
                    Some(rust_patch.base_file_hash.as_str()),
                    Some(rust_patch.patch_file_hash.as_str()),
                    Some(rust_patch.patch_storage_uri.as_str()),
                    Some(j as i64),
                );
                if want != got {
                    failures.push(format!(
                        "create case '{}' bundle[{}] patch row {}\n    upstream : {:?}\n    rust     : {:?}",
                        case.description, i, j, want, got,
                    ));
                }
            }
        }
    }

    report(&failures, "POST payload");
}

// =====================================================================================
// 4. PATCH /api/bundles/:id -- the UpdateBundlePayload request body
// =====================================================================================

/// Which camelCase fields `UpdateBundlePayload` captured, i.e. which columns this patch will
/// actually change. `Some(_)` means the key was present — `Some(None)` (an explicit null that
/// CLEARS the column) counts as captured just as much as `Some(Some(v))` does, which is the
/// whole point of the double option.
fn update_payload_present_fields(p: &UpdateBundlePayload) -> Vec<&'static str> {
    let mut present = Vec::new();
    let mut push = |cond: bool, name: &'static str| {
        if cond {
            present.push(name);
        }
    };
    push(p.platform.is_some(), "platform");
    push(p.should_force_update.is_some(), "shouldForceUpdate");
    push(p.enabled.is_some(), "enabled");
    push(p.file_hash.is_some(), "fileHash");
    push(p.git_commit_hash.is_some(), "gitCommitHash");
    push(p.message.is_some(), "message");
    push(p.channel.is_some(), "channel");
    push(p.storage_uri.is_some(), "storageUri");
    push(p.target_app_version.is_some(), "targetAppVersion");
    push(p.fingerprint_hash.is_some(), "fingerprintHash");
    push(p.metadata.is_some(), "metadata");
    push(p.rollout_cohort_count.is_some(), "rolloutCohortCount");
    push(p.target_cohorts.is_some(), "targetCohorts");
    push(p.manifest_storage_uri.is_some(), "manifestStorageUri");
    push(p.manifest_file_hash.is_some(), "manifestFileHash");
    push(p.asset_base_storage_uri.is_some(), "assetBaseStorageUri");
    push(p.patches.is_some(), "patches");
    present
}

#[test]
fn test_update_payload_parity() {
    let mut failures = Vec::new();

    for case in load().update_bundle_cases {
        let body: Value = if case.request_body_is_raw_text {
            match case.request_body.as_str() {
                Some(text) => serde_json::from_str(text).unwrap_or(Value::Null),
                None => Value::Null,
            }
        } else {
            case.request_body.clone()
        };

        // ---- Stage 1: requireBundlePatchPayload (handler.mjs:76-82) is the whole
        // HTTP-layer contract:
        //   * an ARRAY body collapses to its first element,
        //   * a non-object (or an absent first element) is a 400 "Invalid bundle payload",
        //   * an `id` that is present and differs from the route id is a 400 "Bundle id
        //     mismatch" -- `null` counts as present and therefore as a mismatch,
        //   * a matching `id` is STRIPPED, everything else is forwarded verbatim.
        let candidate = match &body {
            Value::Array(items) => items.first().cloned().unwrap_or(Value::Null),
            other => other.clone(),
        };
        let is_object = candidate.is_object();
        let id_present = candidate.get("id").is_some();
        let id_matches = candidate.get("id") == Some(&Value::String(case.target_id.clone()));

        // The HTTP layer rejects on exactly two grounds, each with its own literal message.
        let want_message = if !is_object {
            Some("Invalid bundle payload")
        } else if id_present && !id_matches {
            Some("Bundle id mismatch")
        } else {
            None
        };

        if let Some(message) = want_message {
            if case.status != 400 || case.body != serde_json::json!({ "error": message }) {
                failures.push(format!(
                    "update case '{}' -- RECORDED FIXTURE no longer answers 400 {{\"error\":\"{}\"}} for body {}: status {} body {}",
                    case.description, message, body, case.status, case.body,
                ));
                continue;
            }
            if case.patch_payload.is_some() {
                failures.push(format!(
                    "update case '{}' -- RECORDED FIXTURE shows a rejected body still reaching updateBundle",
                    case.description,
                ));
                continue;
            }
        } else if case.status == 400 {
            failures.push(format!(
                "update case '{}' -- RECORDED FIXTURE answers 400 {} for a body requireBundlePatchPayload accepts: {}",
                case.description, case.body, body,
            ));
            continue;
        }

        // Past the HTTP layer, `updateBundleById` still runs the bundle lookup and
        // assertBundlePersistenceConstraints BEFORE calling the plugin (pluginCore.mjs:208-219),
        // so the payload reaches updateBundle exactly when the whole request succeeds.
        if case.patch_payload.is_some() != (case.status == 200) {
            failures.push(format!(
                "update case '{}' -- RECORDED FIXTURE has status {} but {} an updateBundle payload; the plugin is called if and only if the request succeeds",
                case.description,
                case.status,
                if case.patch_payload.is_some() { "still records" } else { "records no" },
            ));
            continue;
        }
        if let Some(recorded) = &case.patch_payload {
            let mut want_keys: Vec<String> = keys_of(&candidate);
            want_keys.retain(|k| k != "id");
            if sorted(&want_keys) != sorted(&recorded.keys.clone().unwrap_or_default()) {
                failures.push(format!(
                    "update case '{}' -- RECORDED FIXTURE payload keys {:?} are not the body's keys minus 'id' ({:?})",
                    case.description, recorded.keys, want_keys,
                ));
                continue;
            }
        }

        // A merged field only MATTERS if `bundleToRow` has a column for it. This is what
        // establishes that `patchBaseBundleId` & co. are merged-but-not-stored rather than
        // patchable, and it is proven from the recorded rows rather than asserted in a
        // comment. If upstream ever grows a column, this fires before PATCHABLE_KEYS lies.
        for row in &case.persisted.bundles {
            let stray: Vec<String> = keys_of(&row.value)
                .into_iter()
                .filter(|k| !ROW_COLUMNS.contains(&k.as_str()))
                .collect();
            if !stray.is_empty() {
                failures.push(format!(
                    "update case '{}' -- RECORDED FIXTURE persisted a row with columns bundleToRow does not write: {:?}",
                    case.description, stray,
                ));
            }
        }

        // ---- Stage 2a: the Rust mirror of requireBundlePatchPayload must accept and reject
        // exactly the same bodies, with the same message text.
        let rust_payload = require_bundle_patch_payload(body.clone(), &case.target_id);
        let rust_rejected = rust_payload.as_ref().err().copied();
        if rust_rejected != want_message {
            failures.push(format!(
                "update case '{}' -- requireBundlePatchPayload disagrees\n    body     : {}\n    upstream : {:?}\n    rust     : {:?}",
                case.description, body, want_message, rust_rejected,
            ));
            continue;
        }
        let Ok(rust_payload) = rust_payload else {
            continue;
        };

        // The stripped payload itself must match what upstream forwarded, key for key.
        if let Some(recorded) = &case.patch_payload {
            if rust_payload != recorded.value {
                failures.push(format!(
                    "update case '{}' -- the stripped payload differs\n    upstream : {}\n    rust     : {}",
                    case.description, recorded.value, rust_payload,
                ));
                continue;
            }
        }

        // ---- Stage 2b: and the Rust request type must reach the same conclusion about
        // which columns this PATCH changes.
        let Some(recorded) = case.patch_payload else {
            continue;
        };
        let parsed = match serde_json::from_value::<UpdateBundlePayload>(rust_payload) {
            Ok(p) => p,
            Err(err) => {
                failures.push(format!(
                    "update case '{}' -- upstream ACCEPTED this body and patched {:?}, the Rust type REJECTS it\n    body        : {}\n    serde error : {}",
                    case.description, recorded.keys, body, err,
                ));
                continue;
            }
        };
        let upstream_keys = recorded.keys.clone().unwrap_or_default();
        let rust_present = update_payload_present_fields(&parsed);

        for key in &upstream_keys {
            if !PATCHABLE_KEYS.contains(&key.as_str()) {
                // An unknown key. Upstream merges it into the bundle object but bundleToRow
                // drops it before it reaches a column, so serde ignoring it is equivalent.
                continue;
            }
            if !rust_present.contains(&key.as_str()) {
                failures.push(format!(
                    "update case '{}' -- upstream patches '{}' to {} but the Rust type does not capture it, so the column is left unchanged\n    body : {}",
                    case.description,
                    key,
                    candidate.get(key).map(ToString::to_string).unwrap_or_else(|| "<absent>".into()),
                    body,
                ));
            }
        }
        for key in &rust_present {
            if !upstream_keys.iter().any(|k| k == key) {
                failures.push(format!(
                    "update case '{}' -- the Rust type patches '{}' but upstream's payload has no such key\n    upstream keys : {:?}",
                    case.description, key, upstream_keys,
                ));
            }
        }

        // ---- Stage 2c: THE COLUMN VALUES, replayed. This is where the two merge semantics
        // live, and it is the only stage that can tell them apart.
        //
        //   metadata      -> DEEP merged by `merge_bundle_metadata` (upstream `mergeWith`)
        //   targetCohorts -> REPLACED   (upstream `REPLACE_ON_UPDATE_KEYS`)
        //   patches       -> REPLACED   (ditto), as rows rather than a column
        //
        // A case that patches metadata AND targetCohorts in the SAME request is recorded
        // precisely so that unifying the two rules cannot pass: one of the two assertions
        // below has to fail whichever way they are collapsed.
        let stored_row = case
            .persisted
            .bundles
            .iter()
            .find(|r| r.value.get("id") == Some(&Value::String(case.target_id.clone())))
            .map(|r| &r.value);
        let before_row = case
            .before_rows
            .iter()
            .find(|r| r.get("id") == Some(&Value::String(case.target_id.clone())));

        if let (Some(stored_row), Some(before_row)) = (stored_row, before_row) {
            // metadata: MERGE.
            if let Some(patch_metadata) = &parsed.metadata {
                let before = parse_bundle_metadata(before_row.get("metadata"));
                let rust_after = match patch_metadata {
                    // An explicit null resets to `{}` -- NOT NULL with a default upstream.
                    None => serde_json::json!({}),
                    Some(value) => merge_bundle_metadata(before.as_ref(), value),
                };
                let upstream_after = stored_row.get("metadata").cloned().unwrap_or(Value::Null);
                if upstream_after != rust_after {
                    failures.push(format!(
                        "update case '{}' -- the metadata COLUMN ends up different\n    stored before : {}\n    patch value   : {}\n    upstream after: {}\n    rust after    : {}",
                        case.description,
                        before_row.get("metadata").map(ToString::to_string).unwrap_or_else(|| "<absent>".into()),
                        candidate.get("metadata").map(ToString::to_string).unwrap_or_default(),
                        upstream_after,
                        rust_after,
                    ));
                }
            }

            // targetCohorts: REPLACE. `cohorts_to_json` is private, so the comparison is on
            // the value the payload carries, which `build_update_query` binds directly.
            if let Some(patch_cohorts) = &parsed.target_cohorts {
                let rust_after = match patch_cohorts {
                    None => Value::Null,
                    Some(list) => {
                        Value::Array(list.iter().map(|c| Value::String(c.clone())).collect())
                    }
                };
                let upstream_after = stored_row
                    .get("target_cohorts")
                    .cloned()
                    .unwrap_or(Value::Null);
                if upstream_after != rust_after {
                    failures.push(format!(
                        "update case '{}' -- the target_cohorts COLUMN ends up different\n    stored before : {}\n    upstream after: {}\n    rust after    : {}",
                        case.description,
                        before_row.get("target_cohorts").map(ToString::to_string).unwrap_or_else(|| "<absent>".into()),
                        upstream_after,
                        rust_after,
                    ));
                }
            }
        }

        // patches: REPLACE, as rows. Compare against the rows upstream persisted for this
        // bundle, which is `bundleToPatchRows(getBundlePatches(merged))`.
        if let Some(patch_patches) = &parsed.patches {
            let rust_patches = get_bundle_patches(patch_patches.as_ref());
            let upstream_rows: Vec<&Value> = case
                .persisted
                .patches
                .iter()
                .map(|r| &r.value)
                .filter(|r| r.get("bundle_id") == Some(&Value::String(case.target_id.clone())))
                .collect();

            let upstream_bases: Vec<Option<&str>> = upstream_rows
                .iter()
                .map(|r| r.get("base_bundle_id").and_then(Value::as_str))
                .collect();
            let rust_bases: Vec<Option<&str>> = rust_patches
                .iter()
                .map(|p| Some(p.base_bundle_id.as_str()))
                .collect();

            if upstream_bases != rust_bases {
                failures.push(format!(
                    "update case '{}' -- the patch ROWS end up different\n    patch value   : {}\n    upstream after: {:?}\n    rust after    : {:?}",
                    case.description,
                    candidate.get("patches").map(ToString::to_string).unwrap_or_default(),
                    upstream_bases,
                    rust_bases,
                ));
            }
        }
    }

    report(&failures, "PATCH payload");
}

// =====================================================================================
// 5. The mutation success bodies and DELETE
// =====================================================================================

/// Every mutating verb answers the same literal body, and DELETE of a bundle that does not
/// exist is a SUCCESS, not a 404: `deleteBundleById` returns early when `getBundleById`
/// finds nothing (pluginCore.mjs:221-229) and the handler answers 200 regardless.
///
/// This is a stage-one check only. The Rust success bodies are `json!({"success": true})`
/// literals inside async handlers with no pure function to call, so they cannot be replayed
/// from here; they are compared by inspection in the parity log instead.
#[test]
fn test_mutation_success_bodies_are_recorded() {
    let mut failures = Vec::new();
    let success = serde_json::json!({ "success": true });
    let fixtures = load();

    for case in &fixtures.create_bundle_cases {
        if case.status == 201 && case.body != success {
            failures.push(format!(
                "create case '{}' -- RECORDED FIXTURE 201 body is {}, not {}",
                case.description, case.body, success,
            ));
        }
    }
    for case in &fixtures.update_bundle_cases {
        if case.status == 200 && case.body != success {
            failures.push(format!(
                "update case '{}' -- RECORDED FIXTURE 200 body is {}, not {}",
                case.description, case.body, success,
            ));
        }
    }
    for case in &fixtures.delete_bundle_cases {
        if case.status != 200 || case.body != success {
            failures.push(format!(
                "delete case '{}' -- RECORDED FIXTURE answers status {} body {}, but upstream always answers 200 {}",
                case.description, case.status, case.body, success,
            ));
            continue;
        }
        // A DELETE that matched nothing must not have reached the plugin at all.
        let existed =
            case.description.contains("does not exist") || case.description.contains("empty store");
        if existed && case.delete_calls != 0 {
            failures.push(format!(
                "delete case '{}' -- RECORDED FIXTURE shows {} deleteBundle call(s) for a bundle that does not exist; upstream returns before calling the plugin",
                case.description, case.delete_calls,
            ));
        }
    }

    report(&failures, "mutation success body");
}

// =====================================================================================
// What a follow-up extraction would unlock
//
// Four private functions in `src/routes/api.rs` hold behaviour this file can only record,
// not replay. Each is already pure, or one parameter away from it, and would be replayable
// the way `decide_update` and `calculate_pagination` already are:
//
//   map_to_client_bundle, parse_bundle_metadata, parse_target_cohorts,
//   get_bundle_patches, require_bundle_patch_payload
//       EXTRACTED. All five were already pure (three of them newly written as mirrors of a
//       named upstream function); they are now `pub` and replayed above. Exporting
//       map_to_client_bundle is what turned this suite from "does the response TYPE describe
//       upstream's body" into "does the row MAPPING reproduce it", and that is what caught
//       the two parse_target_cohorts defects.
//
//   assert_bundle_persistence_constraints(...) -> Result<(), String>
//       Still private, still pure. Exporting it would replay every constraint case in
//       createBundleCases and updateBundleCases against upstream's exact message text --
//       which currently matches by inspection only. Worth doing, but the messages agree
//       today and the STATUS deliberately does not (400 here, 500 upstream), so the replay
//       would need that deviation encoded first.
//
//   build_update_query(UpdateBundlePayload, ...) -> Option<QueryBuilder>
//       Still private. Stage 2c above mirrors its "bind the value verbatim" behaviour rather
//       than calling it; if that ever stops being true, export it and call it instead.
//
// =====================================================================================
