// This test verifies that the Rust `decide_update` function makes byte-for-byte the
// same decision as the real @hot-updater/js package (fixtures generated by
// tests/generate_decision_fixtures.mjs) for its appVersionStrategy/fingerprintStrategy
// outputs. It is pure/synchronous, so no DB or S3 is required.
use rn_ota_server_rust::models::Bundle;
use rn_ota_server_rust::routes::check::{decide_update, Decision};
use rn_ota_server_rust::semver::{coerce_version, satisfies};
use serde::Deserialize;

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct FixtureBundle {
    id: String,
    platform: String,
    should_force_update: bool,
    enabled: bool,
    file_hash: String,
    storage_uri: String,
    git_commit_hash: Option<String>,
    message: Option<String>,
    channel: String,
    target_app_version: Option<String>,
    fingerprint_hash: Option<String>,
    rollout_cohort_count: i32,
    target_cohorts: Option<serde_json::Value>,
    manifest_storage_uri: Option<String>,
    manifest_file_hash: Option<String>,
    asset_base_storage_uri: Option<String>,
}

impl From<FixtureBundle> for Bundle {
    fn from(f: FixtureBundle) -> Self {
        Bundle {
            id: f.id,
            app_name: "test-app".to_string(),
            platform: f.platform,
            should_force_update: if f.should_force_update { 1 } else { 0 },
            enabled: if f.enabled { 1 } else { 0 },
            file_hash: f.file_hash,
            git_commit_hash: f.git_commit_hash,
            message: f.message,
            channel: f.channel,
            storage_uri: f.storage_uri,
            target_app_version: f.target_app_version,
            fingerprint_hash: f.fingerprint_hash,
            metadata: None,
            rollout_cohort_count: f.rollout_cohort_count,
            target_cohorts: f.target_cohorts,
            manifest_storage_uri: f.manifest_storage_uri,
            manifest_file_hash: f.manifest_file_hash,
            asset_base_storage_uri: f.asset_base_storage_uri,
            ctime: chrono::Utc::now(),
        }
    }
}

#[derive(Deserialize)]
struct FixtureArgs {
    #[serde(rename = "bundleId")]
    bundle_id: String,
    #[serde(rename = "minBundleId")]
    min_bundle_id: String,
    cohort: Option<String>,
    #[serde(rename = "appVersion")]
    app_version: Option<String>,
    #[serde(rename = "fingerprintHash")]
    fingerprint_hash: Option<String>,
}

#[derive(Deserialize)]
struct ExpectedResult {
    status: String,
    id: String,
    #[serde(rename = "shouldForceUpdate")]
    should_force_update: bool,
}

#[derive(Deserialize)]
struct FixtureCase {
    description: String,
    strategy: String,
    bundles: Vec<FixtureBundle>,
    args: FixtureArgs,
    expected: Option<ExpectedResult>,
}

#[test]
fn test_decision_parity_with_hot_updater_js() {
    let fixtures_json = std::fs::read_to_string("tests/fixtures/decision_fixtures.json")
        .expect("Failed to read tests/fixtures/decision_fixtures.json");
    let cases: Vec<FixtureCase> =
        serde_json::from_str(&fixtures_json).expect("Failed to parse decision_fixtures.json");

    for case in cases {
        let mut candidates: Vec<Bundle> = case.bundles.into_iter().map(Bundle::from).collect();
        candidates.sort_by(|a, b| b.id.cmp(&a.id));

        // As in check_app_version_helper/check_fingerprint_helper, version-or-fingerprint
        // matching is applied before decide_update (the real production pipeline:
        // SQL + semver filter, then decide_update).
        if case.strategy == "appVersion" {
            let app_version = case
                .args
                .app_version
                .clone()
                .unwrap_or_else(|| "1.0.0".to_string());
            let parsed = coerce_version(&app_version).expect("invalid appVersion in fixture");
            candidates.retain(|b| match &b.target_app_version {
                Some(target) => satisfies(&parsed, target),
                None => false,
            });
        } else {
            let fingerprint_hash = case.args.fingerprint_hash.clone().unwrap_or_default();
            candidates.retain(|b| b.fingerprint_hash.as_deref() == Some(fingerprint_hash.as_str()));
        }

        let decision = decide_update(
            &candidates,
            case.args.cohort.as_deref(),
            &case.args.bundle_id,
            &case.args.min_bundle_id,
        );

        match (decision, case.expected) {
            (Decision::NoUpdate, None) => {}
            (Decision::Update(b), Some(exp)) => {
                assert_eq!(
                    exp.status, "UPDATE",
                    "case '{}': status mismatch",
                    case.description
                );
                assert_eq!(
                    b.id, exp.id,
                    "case '{}': UPDATE id mismatch",
                    case.description
                );
                assert_eq!(
                    b.should_force_update != 0,
                    exp.should_force_update,
                    "case '{}': UPDATE shouldForceUpdate mismatch",
                    case.description
                );
            }
            (Decision::Rollback(b), Some(exp)) => {
                assert_eq!(
                    exp.status, "ROLLBACK",
                    "case '{}': status mismatch",
                    case.description
                );
                assert_eq!(
                    b.id, exp.id,
                    "case '{}': ROLLBACK id mismatch",
                    case.description
                );
                assert!(
                    exp.should_force_update,
                    "case '{}': ROLLBACK must force update",
                    case.description
                );
            }
            (Decision::InitRollback, Some(exp)) => {
                assert_eq!(
                    exp.status, "ROLLBACK",
                    "case '{}': status mismatch",
                    case.description
                );
                assert_eq!(
                    exp.id, "00000000-0000-0000-0000-000000000000",
                    "case '{}': InitRollback id mismatch",
                    case.description
                );
                assert!(
                    exp.should_force_update,
                    "case '{}': InitRollback must force update",
                    case.description
                );
            }
            (decision, expected) => {
                panic!(
                    "case '{}': decision/expected shape mismatch -- decision: {}, expected: {:?}",
                    case.description,
                    match decision {
                        Decision::Update(_) => "Update",
                        Decision::Rollback(_) => "Rollback",
                        Decision::InitRollback => "InitRollback",
                        Decision::NoUpdate => "NoUpdate",
                    },
                    expected.map(|e| e.status)
                );
            }
        }
    }
}
