// Replays the recorded cursor-pagination behaviour of the real upstream hot-updater packages
// against the Rust CLI API helpers (fixtures generated by tests/generate_pagination_fixtures.mjs).
//
//   paginationCases -- @hot-updater/plugin-core `calculatePagination`      -> calculate_pagination
//   cursorCases     -- `buildCursorPageQuery` + `createPaginatedResult`    -> build_cursor_page_query
//                                                                           + derive_cursor_keys
//   limitParamCases -- @hot-updater/server `parsePositiveIntegerSearchParam` -> parse_positive_integer_param
//
// All three helpers are pure, so this test needs no database. Every mismatch is collected and
// reported together rather than failing at the first one.
use rn_ota_server_rust::routes::api::{
    build_cursor_page_query, calculate_pagination, derive_cursor_keys, parse_boolean_param,
    parse_nullable_string_param, parse_page_param, parse_platform_param,
    parse_positive_integer_param, parse_string_array_param, parse_truthy_string_param, IdFilter,
    NullableStringParam,
};
use serde::Deserialize;

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct ExpectedPagination {
    total: i64,
    has_next_page: bool,
    has_previous_page: bool,
    current_page: i64,
    total_pages: i64,
    // Present only when upstream emitted the key at all -- createPaginatedResult OMITS these
    // rather than setting them to null, which is itself part of the contract.
    #[serde(default)]
    next_cursor: Option<String>,
    #[serde(default)]
    previous_cursor: Option<String>,
}

#[derive(Deserialize)]
struct PaginationCase {
    description: String,
    total: i64,
    limit: i64,
    offset: i64,
    expected: ExpectedPagination,
}

#[derive(Deserialize)]
struct FixtureIdFilter {
    op: String,
    value: String,
}

#[derive(Deserialize)]
struct FixtureCursorPlan {
    #[serde(rename = "idFilter")]
    id_filter: Option<FixtureIdFilter>,
    ascending: bool,
    #[serde(rename = "reverseData")]
    reverse_data: bool,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct CursorCase {
    description: String,
    dataset: Vec<String>,
    limit: i64,
    after: Option<String>,
    before: Option<String>,
    #[allow(dead_code)]
    page: Option<i64>,
    uses_page_branch: bool,
    cursor_plan: Option<FixtureCursorPlan>,
    inner_page_ids: Option<Vec<String>>,
    start_index: i64,
    data: Vec<String>,
    pagination: ExpectedPagination,
    pagination_keys: Vec<String>,
}

#[derive(Deserialize)]
struct ExpectedLimit {
    ok: bool,
    #[serde(default)]
    value: Option<i64>,
    #[serde(default)]
    message: Option<String>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct LimitParamCase {
    description: String,
    key: String,
    raw: Option<String>,
    default_value: i64,
    max_value: i64,
    expected: ExpectedLimit,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct PageParamCase {
    description: String,
    raw: Option<String>,
    /// Upstream accepted a JS number too large to round-trip through an i64. Such cases pin
    /// only the accept/reject decision -- upstream saturates and the offset is clamped to the
    /// last page anyway, so the observable response is unaffected.
    beyond_i64: bool,
    expected: ExpectedLimit,
}

#[derive(Deserialize)]
struct ExpectedStringValue {
    // `ok` is redundant here -- these groups key off the recorded HTTP status instead.
    #[serde(default)]
    value: Option<serde_json::Value>,
    #[serde(default)]
    message: Option<String>,
}

#[derive(Deserialize)]
struct PlatformParamCase {
    description: String,
    raw: Option<String>,
    status: u16,
    expected: ExpectedStringValue,
}

#[derive(Deserialize)]
struct ExpectedBoolean {
    #[serde(default)]
    value: Option<bool>,
    #[serde(default)]
    message: Option<String>,
}

#[derive(Deserialize)]
struct BooleanParamCase {
    description: String,
    key: String,
    raw: Option<String>,
    status: u16,
    expected: ExpectedBoolean,
}

/// `present` distinguishes "no filter at all" from "a filter whose value is SQL NULL" --
/// a bare `value: null` cannot express that difference on its own.
#[derive(Deserialize)]
struct ExpectedNullableString {
    #[serde(default)]
    present: bool,
    #[serde(default)]
    value: Option<String>,
    #[serde(default)]
    #[allow(dead_code)]
    message: Option<String>,
}

#[derive(Deserialize)]
struct NullableStringParamCase {
    description: String,
    key: String,
    raw: Option<String>,
    status: u16,
    expected: ExpectedNullableString,
}

#[derive(Deserialize)]
struct StringArrayParamCase {
    description: String,
    key: String,
    query: String,
    status: u16,
    expected: ExpectedStringValue,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Fixtures {
    pagination_cases: Vec<PaginationCase>,
    cursor_cases: Vec<CursorCase>,
    limit_param_cases: Vec<LimitParamCase>,
    page_param_cases: Vec<PageParamCase>,
    platform_param_cases: Vec<PlatformParamCase>,
    string_array_param_cases: Vec<StringArrayParamCase>,
    boolean_param_cases: Vec<BooleanParamCase>,
    nullable_string_param_cases: Vec<NullableStringParamCase>,
    truthy_string_param_cases: Vec<NullableStringParamCase>,
}

fn load() -> Fixtures {
    let json = std::fs::read_to_string("tests/fixtures/pagination_fixtures.json")
        .expect("Failed to read tests/fixtures/pagination_fixtures.json");
    serde_json::from_str(&json).expect("Failed to parse pagination_fixtures.json")
}

/// `IdFilter` carries no derives in the contract, so reduce it to a comparable pair.
fn id_filter_parts(filter: &IdFilter) -> (&'static str, Option<&str>) {
    match filter {
        IdFilter::Gt(v) => ("gt", Some(v.as_str())),
        IdFilter::Lt(v) => ("lt", Some(v.as_str())),
        IdFilter::None => ("none", None),
    }
}

fn report(failures: &[String], what: &str) {
    assert!(
        failures.is_empty(),
        "{} of the recorded upstream {} results do not match the Rust implementation:\n\n{}\n",
        failures.len(),
        what,
        failures.join("\n\n")
    );
}

#[test]
fn test_calculate_pagination_parity() {
    let mut failures = Vec::new();

    for case in load().pagination_cases {
        let actual = calculate_pagination(case.total, case.limit, case.offset);
        let e = &case.expected;

        if actual.total != e.total
            || actual.has_next_page != e.has_next_page
            || actual.has_previous_page != e.has_previous_page
            || actual.current_page != e.current_page
            || actual.total_pages != e.total_pages
        {
            failures.push(format!(
                "case '{}'\n    input    : total={} limit={} offset={}\n    upstream : total={} hasNextPage={} hasPreviousPage={} currentPage={} totalPages={}\n    rust     : total={} hasNextPage={} hasPreviousPage={} currentPage={} totalPages={}",
                case.description,
                case.total,
                case.limit,
                case.offset,
                e.total,
                e.has_next_page,
                e.has_previous_page,
                e.current_page,
                e.total_pages,
                actual.total,
                actual.has_next_page,
                actual.has_previous_page,
                actual.current_page,
                actual.total_pages,
            ));
        }
    }

    report(&failures, "calculatePagination");
}

#[test]
fn test_cursor_page_query_parity() {
    let mut failures = Vec::new();

    for case in load().cursor_cases {
        // The `page` branch ignores the cursor entirely and never calls buildCursorPageQuery,
        // so only the pagination arithmetic is replayed for those cases.
        if !case.uses_page_branch {
            let expected_plan = case
                .cursor_plan
                .as_ref()
                .expect("a non-page case must have recorded a cursor plan");

            let plan = build_cursor_page_query(
                case.after.as_deref(),
                case.before.as_deref(),
                true, // upstream's DEFAULT_DESC_ORDER
            );

            let (actual_op, actual_value) = id_filter_parts(&plan.id_filter);
            let (expected_op, expected_value) = match &expected_plan.id_filter {
                Some(f) => (f.op.as_str(), Some(f.value.as_str())),
                None => ("none", None),
            };

            if actual_op != expected_op
                || actual_value != expected_value
                || plan.ascending != expected_plan.ascending
                || plan.reverse_data != expected_plan.reverse_data
            {
                failures.push(format!(
                    "case '{}' -- cursor plan\n    input    : after={:?} before={:?} descending=true\n    upstream : idFilter={}({:?}) ascending={} reverseData={}\n    rust     : idFilter={}({:?}) ascending={} reverseData={}",
                    case.description,
                    case.after,
                    case.before,
                    expected_op,
                    expected_value,
                    expected_plan.ascending,
                    expected_plan.reverse_data,
                    actual_op,
                    actual_value,
                    plan.ascending,
                    plan.reverse_data,
                ));
                continue;
            }

            // Apply the plan to the dataset the way a SQL query would, and check it
            // reproduces the rows upstream's inner query actually returned.
            let mut matching: Vec<&String> = case
                .dataset
                .iter()
                .filter(|id| match &plan.id_filter {
                    IdFilter::Gt(v) => id.as_str() > v.as_str(),
                    IdFilter::Lt(v) => id.as_str() < v.as_str(),
                    IdFilter::None => true,
                })
                .collect();
            matching.sort();
            if !plan.ascending {
                matching.reverse();
            }

            let inner: Vec<String> = matching
                .into_iter()
                .take(case.limit as usize)
                .cloned()
                .collect();

            let expected_inner = case
                .inner_page_ids
                .as_ref()
                .expect("a non-page case must have recorded the inner page ids");

            if &inner != expected_inner {
                failures.push(format!(
                    "case '{}' -- inner query rows\n    plan     : idFilter={}({:?}) ascending={} limit={}\n    upstream : [{}]\n    rust     : [{}]",
                    case.description,
                    actual_op,
                    actual_value,
                    plan.ascending,
                    case.limit,
                    expected_inner.join(", "),
                    inner.join(", "),
                ));
                continue;
            }

            let mut page = inner;
            if plan.reverse_data {
                page.reverse();
            }

            if page != case.data {
                failures.push(format!(
                    "case '{}' -- page rows after reverseData={}\n    upstream : [{}]\n    rust     : [{}]",
                    case.description,
                    plan.reverse_data,
                    case.data.join(", "),
                    page.join(", "),
                ));
            }
        }

        // The pagination object upstream built from (total, limit, startIndex).
        let actual = calculate_pagination(case.pagination.total, case.limit, case.start_index);
        let e = &case.pagination;

        if actual.total != e.total
            || actual.has_next_page != e.has_next_page
            || actual.has_previous_page != e.has_previous_page
            || actual.current_page != e.current_page
            || actual.total_pages != e.total_pages
        {
            failures.push(format!(
                "case '{}' -- pagination\n    input    : total={} limit={} startIndex={}\n    upstream : hasNextPage={} hasPreviousPage={} currentPage={} totalPages={}\n    rust     : hasNextPage={} hasPreviousPage={} currentPage={} totalPages={}",
                case.description,
                e.total,
                case.limit,
                case.start_index,
                e.has_next_page,
                e.has_previous_page,
                e.current_page,
                e.total_pages,
                actual.has_next_page,
                actual.has_previous_page,
                actual.current_page,
                actual.total_pages,
            ));
        }
    }

    report(&failures, "cursor page query");
}

/// Upstream's `createPaginatedResult` OMITS `nextCursor`/`previousCursor` rather than setting
/// them to null:
///
/// ```js
/// const nextCursor     = data.length > 0 && startIndex + data.length < total ? data.at(-1)?.id : void 0;
/// const previousCursor = data.length > 0 && startIndex > 0 ? data[0]?.id : void 0;
/// return { data, pagination: { ...pagination, ...nextCursor ? { nextCursor } : {}, ...previousCursor ? { previousCursor } : {} } };
/// ```
///
/// An OMITTED key and a `null` one are not the same thing to a client that distinguishes
/// `undefined` from `null`, so the fixture records the exact key set upstream produced
/// (`paginationKeys`) and this test maps "key absent" to `None`. `derive_cursor_keys` must
/// therefore return `None` in exactly the cases where upstream emitted no key at all.
#[test]
fn test_cursor_keys_parity() {
    let mut failures = Vec::new();

    // A JS-truthy cursor: `if (cursor.after)` treats an empty string as absent.
    let truthy = |c: &Option<String>| c.as_deref().is_some_and(|s| !s.is_empty());

    for case in load().cursor_cases {
        let total = case.pagination.total;
        let rows = case.data.len() as i64;
        let has_next_key = case.pagination_keys.iter().any(|k| k == "nextCursor");
        let has_prev_key = case.pagination_keys.iter().any(|k| k == "previousCursor");

        // Expected key presence, and the value each key should carry.
        let (expect_next, expect_prev, want_next, want_prev) = if case.data.is_empty() {
            // The empty-page branch echoes the SUPPLIED cursor back.
            (
                truthy(&case.before),
                truthy(&case.after),
                case.before.clone(),
                case.after.clone(),
            )
        } else {
            (
                case.start_index + rows < total,
                case.start_index > 0,
                case.data.last().cloned(),
                case.data.first().cloned(),
            )
        };

        // First: the RECORDED data must obey upstream's documented rule. This is a guard on
        // the fixture itself -- if a regeneration against a newer upstream ever changes the
        // rule, this fires before the Rust comparison muddies the diagnosis.
        if has_next_key != expect_next || has_prev_key != expect_prev {
            failures.push(format!(
                "case '{}' -- RECORDED FIXTURE violates the documented upstream rule\n    total={} startIndex={} rows={} after={:?} before={:?}\n    recorded keys : nextCursor={} previousCursor={}\n    rule expects  : nextCursor={} previousCursor={}",
                case.description,
                total,
                case.start_index,
                rows,
                case.after,
                case.before,
                has_next_key,
                has_prev_key,
                expect_next,
                expect_prev,
            ));
            continue;
        }
        if (expect_next && case.pagination.next_cursor != want_next)
            || (expect_prev && case.pagination.previous_cursor != want_prev)
        {
            failures.push(format!(
                "case '{}' -- RECORDED FIXTURE carries unexpected cursor values\n    nextCursor     : recorded {:?}, rule says {:?}\n    previousCursor : recorded {:?}, rule says {:?}",
                case.description,
                case.pagination.next_cursor,
                want_next,
                case.pagination.previous_cursor,
                want_prev,
            ));
            continue;
        }

        // Then the actual parity check. A key upstream omitted is None on the Rust side; the
        // fixture's Option is already None for an absent key, so this comparison pins the
        // omitted-vs-null distinction as well as the values.
        let keys = derive_cursor_keys(
            total,
            case.start_index,
            &case.data,
            case.after.as_deref(),
            case.before.as_deref(),
        );

        if keys.next_cursor != case.pagination.next_cursor
            || keys.previous_cursor != case.pagination.previous_cursor
        {
            failures.push(format!(
                "case '{}'\n    input    : total={} startIndex={} rows=[{}] after={:?} before={:?}\n    upstream : nextCursor={:?} previousCursor={:?}\n    rust     : nextCursor={:?} previousCursor={:?}",
                case.description,
                total,
                case.start_index,
                case.data.join(", "),
                case.after,
                case.before,
                case.pagination.next_cursor,
                case.pagination.previous_cursor,
                keys.next_cursor,
                keys.previous_cursor,
            ));
        }
    }

    report(&failures, "cursor keys");
}

#[test]
fn test_limit_param_parity() {
    let mut failures = Vec::new();

    for case in load().limit_param_cases {
        let actual = parse_positive_integer_param(
            &case.key,
            case.raw.as_deref(),
            case.default_value,
            case.max_value,
        );

        let matches = match (&actual, case.expected.ok) {
            (Ok(v), true) => Some(*v) == case.expected.value,
            (Err(m), false) => Some(m.clone()) == case.expected.message,
            _ => false,
        };

        if !matches {
            let upstream = if case.expected.ok {
                format!("Ok({:?})", case.expected.value)
            } else {
                format!("Err({:?})", case.expected.message)
            };
            let rust = match &actual {
                Ok(v) => format!("Ok({})", v),
                Err(m) => format!("Err({:?})", m),
            };
            failures.push(format!(
                "case '{}'\n    input    : key={} raw={:?} default={} max={}\n    upstream : {}\n    rust     : {}",
                case.description,
                case.key,
                case.raw,
                case.default_value,
                case.max_value,
                upstream,
                rust,
            ));
        }
    }

    report(&failures, "parsePositiveIntegerSearchParam");
}

#[test]
fn test_page_param_parity() {
    let mut failures = Vec::new();

    for case in load().page_param_cases {
        let actual = parse_page_param(case.raw.as_deref());

        let matches = match (&actual, case.expected.ok) {
            // Beyond-i64 values pin the accept/reject decision only.
            (Ok(Some(_)), true) if case.beyond_i64 => true,
            (Ok(v), true) => *v == case.expected.value,
            (Err(m), false) => Some(m.clone()) == case.expected.message,
            _ => false,
        };

        if !matches {
            let upstream = if case.expected.ok {
                if case.beyond_i64 {
                    "Ok(Some(<beyond i64, value not pinned>))".to_string()
                } else {
                    format!("Ok({:?})", case.expected.value)
                }
            } else {
                format!("Err({:?})", case.expected.message)
            };
            let rust = match &actual {
                Ok(v) => format!("Ok({:?})", v),
                Err(m) => format!("Err({:?})", m),
            };
            failures.push(format!(
                "case '{}'\n    input    : raw={:?}\n    upstream : {}\n    rust     : {}",
                case.description, case.raw, upstream, rust,
            ));
        }
    }

    report(&failures, "page query parameter");
}

/// `platform`, the repeated-array parameters (`idIn`, `targetAppVersionIn`) and the boolean
/// parameters (`enabled`, `targetAppVersionNotNull`), replayed against their Rust mirrors.
///
/// TWO-STAGE STRUCTURE -- please keep it. Each case is checked first against the documented
/// upstream rule (does the RECORDED fixture still obey it?) and only then against the Rust
/// function. Collapsing these into one assertion would make two very different failures
/// present identically:
///
///   * "upstream moved" -- a regeneration against a newer hot-updater changed the rule. The
///     fixture is the new ground truth and the Rust side must follow it.
///   * "we regressed"   -- the fixture is unchanged and Rust drifted away from it.
///
/// The stage-one messages say RECORDED FIXTURE explicitly so the diagnosis is unambiguous
/// before the Rust comparison ever runs. `test_cursor_keys_parity` is built the same way.
#[test]
fn test_query_param_parity() {
    let mut failures = Vec::new();
    let fixtures = load();

    for case in fixtures.platform_param_cases {
        let accepted = case.status == 200;
        let should_accept = matches!(case.raw.as_deref(), None | Some("ios") | Some("android"));

        // Stage 1: the recorded fixture must still obey upstream's documented rule.
        if accepted != should_accept {
            failures.push(format!(
                "platform case '{}' -- RECORDED FIXTURE violates the documented upstream rule: raw={:?} recorded status {} but only absent/ios/android may be accepted",
                case.description, case.raw, case.status,
            ));
            continue;
        }
        let want_message = format!(
            "Invalid platform: {}. Expected 'ios' or 'android'.",
            case.raw.as_deref().unwrap_or("")
        );
        if !accepted && case.expected.message.as_deref() != Some(want_message.as_str()) {
            failures.push(format!(
                "platform case '{}' -- RECORDED FIXTURE carries 400 message {:?}, not the upstream template {:?}",
                case.description, case.expected.message, want_message,
            ));
            continue;
        }

        // Stage 2: the Rust mirror must reproduce it.
        let actual = parse_platform_param(case.raw.as_deref());
        let expected: Result<Option<String>, String> = if accepted {
            Ok(case
                .expected
                .value
                .as_ref()
                .and_then(|v| v.as_str())
                .map(str::to_string))
        } else {
            Err(case.expected.message.clone().unwrap_or_default())
        };

        if actual != expected {
            failures.push(format!(
                "platform case '{}'\n    input    : raw={:?}\n    upstream : {:?}\n    rust     : {:?}",
                case.description, case.raw, expected, actual,
            ));
        }
    }

    for case in fixtures.string_array_param_cases {
        if case.status != 200 {
            failures.push(format!(
                "array case '{}' -- RECORDED FIXTURE unexpectedly has status {} for query {:?}",
                case.description, case.status, case.query,
            ));
            continue;
        }

        // The values upstream would have seen, reconstructed from the query string the way
        // searchParams.getAll does: one element per occurrence of the key, commas untouched.
        let occurrences: Vec<String> = case
            .query
            .trim_start_matches('?')
            .split('&')
            .filter(|kv| !kv.is_empty())
            .filter_map(|kv| kv.split_once('='))
            .filter(|(k, _)| *k == case.key)
            .map(|(_, v)| percent_decode(v))
            .collect();

        let recorded: Option<Vec<String>> = case.expected.value.as_ref().and_then(|v| {
            v.as_array().map(|a| {
                a.iter()
                    .filter_map(|x| x.as_str().map(str::to_string))
                    .collect()
            })
        });

        // Stage 1: repetition count decides the element count -- commas never split.
        if recorded.as_ref().map(Vec::len).unwrap_or(0) != occurrences.len() {
            failures.push(format!(
                "array case '{}' -- RECORDED FIXTURE violates the getAll rule: query {:?} repeats '{}' {} time(s) but recorded {} element(s)",
                case.description,
                case.query,
                case.key,
                occurrences.len(),
                recorded.as_ref().map(Vec::len).unwrap_or(0),
            ));
            continue;
        }

        // Stage 2: the Rust mirror must reproduce it.
        let actual = parse_string_array_param(&occurrences);
        if actual != recorded {
            failures.push(format!(
                "array case '{}'\n    input    : query={:?} -> getAll({}) = {:?}\n    upstream : {:?}\n    rust     : {:?}",
                case.description, case.query, case.key, occurrences, recorded, actual,
            ));
        }
    }

    // Boolean parameters: only the exact strings "true"/"false", and the 400 names the key.
    for case in fixtures.boolean_param_cases {
        let accepted = case.status == 200;
        let should_accept = matches!(case.raw.as_deref(), None | Some("true") | Some("false"));

        // Stage 1: the recorded fixture must still obey upstream's documented rule.
        if accepted != should_accept {
            failures.push(format!(
                "boolean case '{}' -- RECORDED FIXTURE violates the documented upstream rule: raw={:?} recorded status {} but only absent/true/false may be accepted",
                case.description, case.raw, case.status,
            ));
            continue;
        }
        let want_message = format!(
            "The '{}' query parameter must be 'true' or 'false'.",
            case.key
        );
        if !accepted && case.expected.message.as_deref() != Some(want_message.as_str()) {
            failures.push(format!(
                "boolean case '{}' -- RECORDED FIXTURE carries 400 message {:?}, not the upstream template {:?}",
                case.description, case.expected.message, want_message,
            ));
            continue;
        }

        // Stage 2: the Rust mirror must reproduce it.
        let actual = parse_boolean_param(&case.key, case.raw.as_deref());
        let expected: Result<Option<bool>, String> = if accepted {
            Ok(case.expected.value)
        } else {
            Err(case.expected.message.clone().unwrap_or_default())
        };

        if actual != expected {
            failures.push(format!(
                "boolean case '{}'\n    input    : key={} raw={:?}\n    upstream : {:?}\n    rust     : {:?}",
                case.description, case.key, case.raw, expected, actual,
            ));
        }
    }

    // ---------------------------------------------------------------------------------
    // THE HANDLER HAS TWO DIFFERENT EMPTINESS/NULL RULES. Do not merge them.
    //
    //     ?targetAppVersion=null  ->  SQL `IS NULL`
    //     ?channel=null           ->  a filter on the literal four-character string "null"
    //
    // Same input, same handler, different meaning. Upstream folds `targetAppVersion` and
    // `fingerprintHash` in with `!== undefined` after `parseNullableStringSearchParam`
    // (handler.mjs:55-59,173,178), while `channel` and `platform` are folded with JS
    // truthiness (`...channel && { channel }`, handler.mjs:170). Consequences:
    //
    //                       ?x=          ?x=null              ?x=NULL / ?x=" null "
    //     nullable rule     real filter  SQL IS NULL          literal string (no fold/trim)
    //     truthy rule       NO filter    literal string       literal string
    //
    // Anyone consolidating these into one "helpful" parser breaks exactly one of them, and
    // the only thing that catches it is a test calling BOTH functions. That is why the
    // fixtures carry two separate groups and this test replays each against its own mirror:
    // `parse_nullable_string_param` below, `parse_truthy_string_param` further down.
    // ---------------------------------------------------------------------------------

    // Nullable string parameters. Upstream maps the EXACT lowercase "null" to SQL NULL and
    // guards these fields with `!== undefined`, so the empty string is a real filter.
    for case in fixtures.nullable_string_param_cases {
        if case.status != 200 {
            failures.push(format!(
                "nullable case '{}' -- RECORDED FIXTURE unexpectedly has status {}",
                case.description, case.status,
            ));
            continue;
        }

        // Stage 1: the recorded fixture must still obey upstream's documented rule.
        let want_present = case.raw.is_some();
        let want_null = case.raw.as_deref() == Some("null");
        if case.expected.present != want_present
            || (case.expected.value.is_none() && case.expected.present) != want_null
        {
            failures.push(format!(
                "nullable case '{}' -- RECORDED FIXTURE violates the documented upstream rule: raw={:?} recorded present={} value={:?}, but only an absent parameter drops the filter and only the exact lowercase \"null\" becomes SQL NULL",
                case.description, case.raw, case.expected.present, case.expected.value,
            ));
            continue;
        }

        // Stage 2: the Rust mirror must reproduce it.
        let actual = parse_nullable_string_param(case.raw.as_deref());
        let expected = if !case.expected.present {
            NullableStringParam::Absent
        } else {
            match &case.expected.value {
                None => NullableStringParam::Null,
                Some(v) => NullableStringParam::Value(v.clone()),
            }
        };

        if actual != expected {
            failures.push(format!(
                "nullable case '{}'\n    input    : key={} raw={:?}\n    upstream : {:?}\n    rust     : {:?}",
                case.description, case.key, case.raw, expected, actual,
            ));
        }
    }

    // Truthy string parameters (`channel`), folded in upstream with `...channel && {channel}`
    // rather than `!== undefined` -- the other of the handler's two emptiness rules. See the
    // block comment above the nullable loop for why these must stay separate.
    for case in fixtures.truthy_string_param_cases {
        if case.status != 200 {
            failures.push(format!(
                "truthy case '{}' -- RECORDED FIXTURE unexpectedly has status {}",
                case.description, case.status,
            ));
            continue;
        }

        // A non-empty string is truthy in JS -- including "0", " " and "null", which is what
        // keeps this rule distinct from the nullable-string one above.
        let want_present = case.raw.as_deref().is_some_and(|s| !s.is_empty());
        if case.expected.present != want_present {
            failures.push(format!(
                "truthy case '{}' -- RECORDED FIXTURE violates the documented upstream rule: raw={:?} recorded present={}, but only an absent or empty value drops the filter",
                case.description, case.raw, case.expected.present,
            ));
            continue;
        }
        if case.expected.present && case.expected.value.as_deref() != case.raw.as_deref() {
            failures.push(format!(
                "truthy case '{}' -- RECORDED FIXTURE altered the value: raw={:?} but recorded {:?}; this rule passes the string through verbatim (no null mapping)",
                case.description, case.raw, case.expected.value,
            ));
            continue;
        }

        // Stage 2: the Rust mirror must reproduce it. Note this must NOT map "null" to
        // anything special -- that is the nullable rule, and conflating the two is exactly
        // what these two groups exist to prevent.
        let actual = parse_truthy_string_param(case.raw.as_deref());
        let expected: Option<String> = if case.expected.present {
            case.expected.value.clone()
        } else {
            None
        };

        if actual != expected {
            failures.push(format!(
                "truthy case '{}'\n    input    : key={} raw={:?}\n    upstream : {:?}\n    rust     : {:?}",
                case.description, case.key, case.raw, expected, actual,
            ));
        }
    }

    report(&failures, "query parameter");
}

/// Minimal percent-decoding for the fixture query strings (they only ever contain %XX and
/// no `+`-as-space), so the getAll reconstruction sees the same values the browser would.
fn percent_decode(s: &str) -> String {
    let bytes = s.as_bytes();
    let mut out = Vec::with_capacity(bytes.len());
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'%' && i + 2 < bytes.len() {
            if let Ok(byte) = u8::from_str_radix(&s[i + 1..i + 3], 16) {
                out.push(byte);
                i += 3;
                continue;
            }
        }
        out.push(bytes[i]);
        i += 1;
    }
    String::from_utf8(out).expect("fixture query strings are valid UTF-8")
}
