// This test verifies that the Rust `coerce_version`/`satisfies` functions
// (src/semver.rs) produce byte-for-byte the same result as the real `semver` npm
// package (fixtures generated by tests/generate_semver_fixtures.mjs) for its
// coerce()/satisfies() behavior. It is pure/synchronous, so no DB or S3 is required.
use rn_ota_server_rust::semver::{coerce_version, satisfies};
use serde::Deserialize;

#[derive(Deserialize)]
struct SatisfiesCase {
    description: String,
    #[serde(rename = "currentVersion")]
    current_version: String,
    #[serde(rename = "targetRange")]
    target_range: String,
    expected: bool,
    group: String,
}

#[derive(Deserialize)]
struct CoerceCase {
    description: String,
    input: String,
    expected: Option<String>,
    group: String,
}

#[derive(Deserialize)]
struct Fixtures {
    #[serde(rename = "satisfiesCases")]
    satisfies_cases: Vec<SatisfiesCase>,
    #[serde(rename = "coerceCases")]
    coerce_cases: Vec<CoerceCase>,
}

fn load_fixtures() -> Fixtures {
    let json = std::fs::read_to_string("tests/fixtures/semver_fixtures.json")
        .expect("Failed to read tests/fixtures/semver_fixtures.json");
    serde_json::from_str(&json).expect("Failed to parse semver_fixtures.json")
}

#[test]
fn test_satisfies_parity_with_node_semver() {
    let fixtures = load_fixtures();

    for case in fixtures
        .satisfies_cases
        .iter()
        .filter(|c| c.group != "known-limitation")
    {
        let actual = match coerce_version(&case.current_version) {
            Some(v) => satisfies(&v, &case.target_range),
            None => false,
        };
        assert_eq!(
            actual, case.expected,
            "case '{}': currentVersion={:?} targetRange={:?} -- expected {}, got {}",
            case.description, case.current_version, case.target_range, case.expected, actual
        );
    }
}

#[test]
fn test_coerce_parity_with_node_semver() {
    let fixtures = load_fixtures();

    for case in fixtures
        .coerce_cases
        .iter()
        .filter(|c| c.group != "known-limitation")
    {
        let actual = coerce_version(&case.input).map(|v| v.to_string());
        assert_eq!(
            actual, case.expected,
            "case '{}': input={:?} -- expected {:?}, got {:?}",
            case.description, case.input, case.expected, actual
        );
    }
}

/// Known limitation: node-semver rejects/truncates numeric components beyond JS's
/// safe-integer limit (2^53-1, ~16 digits); the Rust side uses `u64` (~20 digits),
/// so in these extreme cases (which never occur in real mobile app version strings)
/// there is no bit-for-bit parity. Realistic usage (basic ^/~ ranges, X-range,
/// hyphen range, coerce, exact match, leading-zero rejection) passes with full
/// parity (the two tests above).
#[test]
#[ignore = "known limitation: extremely large numeric components (16+ digits) exceed the JS safe-integer limit and diverge from Rust u64 capacity"]
fn test_known_limitations_overflow_components() {
    let fixtures = load_fixtures();

    for case in fixtures
        .satisfies_cases
        .iter()
        .filter(|c| c.group == "known-limitation")
    {
        let actual = match coerce_version(&case.current_version) {
            Some(v) => satisfies(&v, &case.target_range),
            None => false,
        };
        assert_eq!(actual, case.expected, "case '{}'", case.description);
    }

    for case in fixtures
        .coerce_cases
        .iter()
        .filter(|c| c.group == "known-limitation")
    {
        let actual = coerce_version(&case.input).map(|v| v.to_string());
        assert_eq!(actual, case.expected, "case '{}'", case.description);
    }
}
